services:

  postgres:
    image: postgres:16
    container_name: secrets-postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: laboratorio
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

secrets:
  db_password:
    file: ./secrets/db_password.txt

volumes:
  postgres_data: